/**
 * App-wide constants. Safety-critical values (the helpline) live here and are NEVER
 * generated by the model.
 */

/** Ollama model tag. Change this one line to point at a different local model. */
export const MODEL_TAG = 'gemma3:4b'

/** Local Ollama chat endpoint. Must stay localhost — data never leaves the device. */
export const OLLAMA_URL = 'http://localhost:11434/api/chat'

/**
 * India's government mental-health helpline. Hardcoded on purpose — the model must never
 * invent or alter a helpline number.
 */
export const TELE_MANAS = {
  name: 'Tele-MANAS',
  primary: '14416',
  alternate: '1-800-891-4416',
  note: 'Free & 24/7 · Government of India',
}

/** Always-visible disclaimer shown in the footer. */
export const DISCLAIMER =
  'MindEase supports everyday stress. It is not a substitute for professional care. ' +
  `In distress? Call ${TELE_MANAS.name} ${TELE_MANAS.primary} (free, 24/7).`

/** localStorage key for journal entries. */
export const STORAGE_KEY = 'mindease.entries.v1'
